# Generated by Django 3.1.2 on 2020-10-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201004_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='dogs_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
