# Generated by Django 3.1.2 on 2020-10-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20201005_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
    ]
