# Generated by Django 3.1.2 on 2020-10-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_user_has_full_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_has_full_profile',
            field=models.BooleanField(default=False),
        ),
    ]
