# Generated by Django 3.1.2 on 2020-10-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_user__has_full_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_has_full_profile',
            field=models.BooleanField(null=True),
        ),
    ]
