# Generated by Django 3.1.2 on 2020-10-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20201005_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offset',
            field=models.IntegerField(null=True),
        ),
    ]
