# Generated by Django 3.1.2 on 2020-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_user_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lon',
            field=models.IntegerField(null=True),
        ),
    ]
