# Generated by Django 3.1.2 on 2020-10-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20201013_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_has_full_profile',
            field=models.BooleanField(default=False),
        ),
    ]
