# Generated by Django 3.1.2 on 2020-10-20 12:01

from django.db import migrations, models
import teams.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20201015_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invited',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='dogs_birthday',
            field=models.DateField(validators=[teams.models.keep_limits]),
        ),
    ]
