# Generated by Django 3.1.2 on 2020-10-20 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20201020_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='invited',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invited',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
