# Generated by Django 3.1.2 on 2020-10-22 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_invited_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invited',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 10, 5, 15, 903122), editable=False),
        ),
    ]
