# Generated by Django 3.1.2 on 2020-10-22 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20201022_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invited',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 10, 18, 10, 816835, tzinfo=utc), editable=False),
        ),
    ]
