# Generated by Django 3.1.2 on 2020-10-23 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_auto_20201022_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invited',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 8, 25, 24, 89296, tzinfo=utc), editable=False),
        ),
    ]
