# Generated by Django 3.1.2 on 2020-10-23 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_auto_20201023_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invited',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 14, 10, 17, 20324, tzinfo=utc), editable=False),
        ),
    ]
