# Generated by Django 3.1.2 on 2020-10-23 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_auto_20201023_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dogs_pic',
            field=models.ImageField(blank=True, null=True, upload_to=teams.models.Dog.user_directory_path),
        ),
        migrations.AlterField(
            model_name='invited',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 18, 2, 48, 472428, tzinfo=utc), editable=False),
        ),
    ]
