# Generated by Django 3.1.2 on 2020-10-08 10:34

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_only', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.AlterField(
            model_name='ascription',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_only.composition', verbose_name='Exercise'),
        ),
    ]
