# Generated by Django 3.1.2 on 2020-10-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_only', '0002_auto_20201008_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
