# Generated by Django 3.1.2 on 2020-10-11 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_only', '0003_delete_dog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ascription',
            unique_together={('composition', 'user')},
        ),
    ]
