# Generated by Django 3.1.2 on 2020-10-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_only', '0004_auto_20201011_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
