# Generated by Django 3.1.2 on 2020-10-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_only', '0005_ascription_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='field_set',
            new_name='extra_fields',
        ),
    ]
