# Generated by Django 3.1.2 on 2020-10-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='composition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.composition'),
            preserve_default=False,
        ),
    ]
