# Generated by Django 3.1.2 on 2020-10-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20201006_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='composition',
        ),
    ]
