# Generated by Django 3.1.2 on 2020-10-06 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0005_auto_20201006_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='owner',
            field=models.ForeignKey(default=11, editable=False, on_delete=django.db.models.deletion.CASCADE, to='teams.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ascription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.composition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
