# Generated by Django 3.1.2 on 2020-10-07 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0006_auto_20201006_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascription',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.composition'),
        ),
        migrations.AlterField(
            model_name='ascription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
