# Generated by Django 3.1.2 on 2020-10-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20201007_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='ascription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.ascription'),
            preserve_default=False,
        ),
    ]
