# Generated by Django 3.1.2 on 2020-10-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_only', '0001_initial'),
        ('training', '0008_exercise_ascription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='ascription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_only.ascription'),
        ),
        migrations.DeleteModel(
            name='Ascription',
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
    ]
