# Generated by Django 3.1.2 on 2020-10-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_auto_20201013_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField()),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('id_something', models.IntegerField()),
                ('something', models.CharField(max_length=255)),
            ],
        ),
    ]
