# Generated by Django 3.1.2 on 2020-10-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='id_something',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='something',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='location',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='offset',
        ),
    ]
