# Generated by Django 3.1.2 on 2020-10-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_auto_20201013_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinates',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weather',
        ),
    ]
