# Generated by Django 3.1.2 on 2020-10-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20201013_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
