# Generated by Django 3.1.2 on 2020-10-13 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_exercise_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='datetime',
        ),
        migrations.AddField(
            model_name='exercise',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 19, 19, 27, 352495, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
