# Generated by Django 3.1.2 on 2020-10-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_auto_20201013_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='when',
            field=models.DateTimeField(verbose_name=True),
        ),
    ]
