# Generated by Django 3.1.2 on 2020-10-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20201013_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='when',
            field=models.DateTimeField(),
        ),
    ]
