# Generated by Django 3.1.2 on 2020-10-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_auto_20201013_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='sunrise',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='sunset',
        ),
        migrations.AddField(
            model_name='exercise',
            name='weather',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.weather'),
        ),
    ]
