# Generated by Django 3.1.2 on 2020-10-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20201015_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='humidity',
        ),
    ]
