# Generated by Django 3.1.2 on 2020-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_remove_weather_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='film',
            field=models.URLField(blank=True, null=True, verbose_name='nagranie'),
        ),
    ]
