# Generated by Django 3.1.2 on 2020-10-23 13:00

from django.db import migrations, models
import training.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_exercise_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='when',
            field=models.DateTimeField(validators=[training.models.no_future_exercises]),
        ),
    ]
