# Generated by Django 3.1.2 on 2020-10-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_auto_20201028_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
    ]
