# Generated by Django 3.1.2 on 2020-10-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_auto_20201028_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-when']},
        ),
    ]
